# Generated by Django 4.2.3 on 2023-07-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
