# Generated by Django 4.2.3 on 2023-08-11 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_contact_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Femele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_f', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Male',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_m', models.CharField(max_length=100, null=True)),
                ('girl', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='chat.femele')),
            ],
        ),
    ]
