# Generated by Django 4.2.3 on 2023-08-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_prod_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prod',
            options={'managed': True, 'ordering': ['price'], 'verbose_name': '7amada', 'verbose_name_plural': '7amadas'},
        ),
        migrations.AlterModelTable(
            name='prod',
            table='',
        ),
    ]
